# docker compose up --build
services:
  node:
    container_name: typedai-dev # name should match the filter in the ./bin/container script
    restart: always
    ports:
      - 4200:4200
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ~/.config/gcloud:/home/typedai/.config/gcloud # Comment out if not using Google Cloud
      # Mount project files but exclude node_modules
      - ./:/home/typedai/:delegated
      - /home/typedai/node_modules
      - /home/typedai/frontend/node_modules
#    environment:
#      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
#      - var=value
