const fs = require('fs');
const path = require('path');

function generateEnvironmentFile() {
    const envVars = {
        version: process.env.npm_package_version,
        API_BASE_URL: process.env.API_BASE_URL,
        GCLOUD_PROJECT: process.env.GCLOUD_PROJECT,
        FIRESTORE_DATABASE: process.env.FIRESTORE_DATABASE,
        AUTH: process.env.AUTH
    };
    console.log(envVars)
    for ([k,v] of Object.entries(envVars)) {
        if (!v) console.error(`${k} is required`);
    }

    const environmentFile = `// This file is auto-generated by ${__filename}
export const env = ${JSON.stringify(envVars, null, 2)};
`;

    const targetPath = path.join(__dirname, '../src/environments/.env.ts');

    try {
        fs.writeFileSync(targetPath, environmentFile);
        console.log(`Environment file generated successfully at ${targetPath}`);
    } catch (error) {
        console.error('Error generating environment file:', error);
        process.exit(1);
    }
}

generateEnvironmentFile();