// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run start:<env>` command
// `npm run start:<env>` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
// Update the script/env.js file to add additional variables to write to the .env.ts file.
import { env } from './.env';

export const environment = {
  production: false,
  gcpProject: env['GCLOUD_PROJECT'],
  firestoreDb: env['FIRESTORE_DATABASE'],
  auth: env['AUTH'],
  apiBaseUrl: env['API_BASE_URL'],
};
