// `.env.ts` is generated by the `npm run write:env` command
// `npm run write:env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
// Update the write:env script in package.json to add additional variables to write to the .env.ts file.
import { env } from './.env';

export const environment = {
  production: true,
  serverUrl: env['SERVER_URL'] || 'http://localhost:3000/api/',
  gcpProject: env['GCLOUD_PROJECT'],
  firestoreDb: env['FIRESTORE_DATABASE'],
  auth: env['AUTH'],
  apiBaseUrl: 'https://api.yourdomain.com', // Adjust this URL for production
};
