// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
// Update the write:env script in package.json to add additional variables to write to the .env.ts file.
import { env } from './.env';

export const environment = {
  production: false,
  serverUrl: env['SERVER_URL'] || 'http://localhost:3000/api',
  gcpProject: env['GCLOUD_PROJECT'],
  firestoreDb: env['FIRESTORE_DATABASE'],
  auth: env['AUTH'],
  apiBaseUrl: 'http://localhost:3000/api/', // Adjust this URL as needed for local development
};
